//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CheckUpEntities : DbContext
    {
        public CheckUpEntities()
            : base("name=CheckUpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Govern> Governs { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<DieaseName> DieaseNames { get; set; }
        public virtual DbSet<HealthProfile> HealthProfiles { get; set; }
        public virtual DbSet<LabBranch> LabBranches { get; set; }
        public virtual DbSet<Laboratory> Laboratories { get; set; }
        public virtual DbSet<ResultFilespath> ResultFilespaths { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<RoushettaPath> RoushettaPaths { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestName> TestNames { get; set; }
    }
}
