//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthProfile
    {
        public HealthProfile()
        {
            this.DieaseNames = new HashSet<DieaseName>();
        }
    
        public long Id { get; set; }
        public Nullable<bool> isSuffreDiabetes { get; set; }
        public Nullable<bool> isSuffrePressure { get; set; }
        public Nullable<bool> isSTakeantiBiotic { get; set; }
        public Nullable<bool> isTakehaemophilia { get; set; }
        public string userId { get; set; }
    
        public virtual ICollection<DieaseName> DieaseNames { get; set; }
    }
}
