//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabBranch
    {
        public LabBranch()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public long Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string govern { get; set; }
        public string image { get; set; }
        public string phone { get; set; }
        public Nullable<bool> isAvailableFromHome { get; set; }
        public string timeFrom { get; set; }
        public string timeTo { get; set; }
        public string holidays { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public string FireBaseId { get; set; }
        public Nullable<long> LabId { get; set; }
        public Nullable<long> addressId { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<long> reviewId { get; set; }
        public Nullable<long> governId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Govern Govern1 { get; set; }
        public virtual Laboratory Laboratory { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
