//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratory
    {
        public Laboratory()
        {
            this.LabBranches = new HashSet<LabBranch>();
            this.Tests = new HashSet<Test>();
        }
    
        public long Id { get; set; }
        public string name { get; set; }
        public string formalReferencePathId { get; set; }
        public Nullable<long> formalRefrencePathIdDB { get; set; }
        public string specialTests { get; set; }
        public string image { get; set; }
        public string branches { get; set; }
        public string FireBaseId { get; set; }
        public string hotline { get; set; }
        public Nullable<int> rating { get; set; }
    
        public virtual ICollection<LabBranch> LabBranches { get; set; }
        public virtual ICollection<Test> Tests { get; set; }
    }
}
