//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string description { get; set; }
        public Nullable<int> rateNumber { get; set; }
        public string userId { get; set; }
        public Nullable<long> UserIdDB { get; set; }
        public Nullable<long> LabBranchId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    
        public virtual LabBranch LabBranch { get; set; }
    }
}
