//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.ResultFilespaths = new HashSet<ResultFilespath>();
            this.RoushettaPaths = new HashSet<RoushettaPath>();
            this.TestNames = new HashSet<TestName>();
        }
    
        public long Id { get; set; }
        public string userId { get; set; }
        public Nullable<long> userIdDB { get; set; }
        public string description { get; set; }
        public Nullable<bool> isFromHome { get; set; }
        public string dateRequest { get; set; }
        public string timeRequest { get; set; }
        public string dateForTakingSample { get; set; }
        public string timeForTakingSample { get; set; }
        public string dateResult { get; set; }
        public string timeResult { get; set; }
        public string branchId { get; set; }
        public Nullable<long> branchIdDB { get; set; }
        public string labId { get; set; }
        public Nullable<long> labIdDB { get; set; }
        public Nullable<long> addressId { get; set; }
        public string hba1c { get; set; }
        public string status { get; set; }
        public Nullable<bool> isNotified { get; set; }
        public string totalCost { get; set; }
        public string precautions { get; set; }
        public string employeeId { get; set; }
        public string radioReason { get; set; }
        public string generatedCode { get; set; }
        public Nullable<long> timeStampRequest { get; set; }
        public string refuseReason { get; set; }
        public Nullable<System.DateTime> dateRequestFormat { get; set; }
        public Nullable<bool> isNotifiedLab { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Laboratory Laboratory { get; set; }
        public virtual ICollection<ResultFilespath> ResultFilespaths { get; set; }
        public virtual ICollection<RoushettaPath> RoushettaPaths { get; set; }
        public virtual ICollection<TestName> TestNames { get; set; }
    }
}
